export {
  advanceEffects,
  advancePowerup,
  claimPowerup,
  distanceToPowerup,
  FLIGHT_MS,
  forfeitPowerup,
  grantPowerup,
  hasMagnet,
  isFlying,
  isPowerupLive,
  MAGNET_MS,
  NO_EFFECTS,
  placePowerup,
  POWERUP_KINDS,
  POWERUP_LEAD_FACTOR,
  POWERUPS,
  SHIELD_CHARGES,
  spendShield,
} from './powerup';
export type {
  ActivePowerup,
  PlacePowerupInput,
  PlacePowerupResult,
  PowerupAdvanceInput,
  PowerupDefinition,
  PowerupEffects,
  PowerupEvent,
  PowerupKind,
  PowerupStatus,
} from './powerup';
