export {
  advanceCoin,
  COIN_LEAD_FACTOR,
  COIN_UNIT_SPACING_METERS,
  COINS_PER_LINE,
  coinRemainingMs,
  coinsDropped,
  coinsTaken,
  collectsCoins,
  commitCoin,
  distanceToCoins,
  isCoinLive,
  placeCoin,
  resolveCoin,
} from './coin';
export type {
  ActiveCoin,
  CoinAdvanceInput,
  CoinAdvanceResult,
  CoinEvent,
  CoinResolution,
  CoinStatus,
  CoinUnit,
  PlaceCoinInput,
  PlaceCoinResult,
} from './coin';
